Host:   127.0.0.1
Port:   8181
LogLevel: debug
FileName: calenar.log
GrpcServer: 127.0.0.1:5051

DB:
  Server: "127.0.0.1:54441"
  User: "postgres"
  Pass: "postgres"
  Database: "calendar"
  TimeoutConnect: 5
  TimeoutExecute: 10
  Type: "Postgres"

rmq:
  host_port: "192.168.1.124:5672"
  timeout_connect: 10
  user: "guest"
  pass: "guest"
  queue: "sendEvent"