Host:   127.0.0.1
Port:   8181

log:
  Level: debug
  FileName: calenar.log

grps:
  Server: 127.0.0.1:5051

db:
  Server: "127.0.0.1:54441"
  User: "postgres"
  Pass: "postgres"
  Database: "calendar"
  TimeoutConnect: 5
  TimeoutExecute: 10
  Type: "Postgres"

rmq:
  host_port: "192.168.1.31:5672"
  timeout_connect: 10
  user: "guest"
  pass: "guest"
  queue1: "sendEvent"
  queue2: "reciveEvent"

scheduler:
  checkInSeconds: 10
  notifyInMinute: 10

